services:
  backend:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
  
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smarthint
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - db
      - frontend