/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProductCreateImport } from './routes/product.create'
import { Route as ProductProductIdEditImport } from './routes/product.$productId.edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductCreateRoute = ProductCreateImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => rootRoute,
} as any)

const ProductProductIdEditRoute = ProductProductIdEditImport.update({
  id: '/product/$productId/edit',
  path: '/product/$productId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/product/create': {
      id: '/product/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof ProductCreateImport
      parentRoute: typeof rootRoute
    }
    '/product/$productId/edit': {
      id: '/product/$productId/edit'
      path: '/product/$productId/edit'
      fullPath: '/product/$productId/edit'
      preLoaderRoute: typeof ProductProductIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/create': typeof ProductCreateRoute
  '/product/$productId/edit': typeof ProductProductIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/create': typeof ProductCreateRoute
  '/product/$productId/edit': typeof ProductProductIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/product/create': typeof ProductCreateRoute
  '/product/$productId/edit': typeof ProductProductIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product/create' | '/product/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product/create' | '/product/$productId/edit'
  id: '__root__' | '/' | '/product/create' | '/product/$productId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductCreateRoute: typeof ProductCreateRoute
  ProductProductIdEditRoute: typeof ProductProductIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductCreateRoute: ProductCreateRoute,
  ProductProductIdEditRoute: ProductProductIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/product/create",
        "/product/$productId/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/product/create": {
      "filePath": "product.create.tsx"
    },
    "/product/$productId/edit": {
      "filePath": "product.$productId.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
