"""adding forgotten parameters

Revision ID: 3200f2be7c0f
Revises: a1e96eecbc4c
Create Date: 2025-01-23 00:58:21.586700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3200f2be7c0f'
down_revision = 'a1e96eecbc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ean', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.drop_index('idx_product_name')
        batch_op.create_index('idx_product_ean', ['ean'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_product_ean')
        batch_op.create_index('idx_product_name', ['name'], unique=False)
        batch_op.drop_column('description')
        batch_op.drop_column('price')
        batch_op.drop_column('ean')

    # ### end Alembic commands ###
